security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: App\Security\CustomAuthenticationFailureHandler
            provider: app_user_provider

        api:
            pattern: ^/api
            stateless: true
            jwt: ~
            provider: app_user_provider

    role_hierarchy:
        ROLE_OWNER: ROLE_ADMIN
        ROLE_ADMIN: ROLE_EXPERT
        ROLE_EXPERT: ROLE_CLIENT
        ROLE_CLIENT: ROLE_USER
        PUBLIC_ACCESS: PUBLIC_ACCESS

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/verify-email, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/resend-verification, roles: PUBLIC_ACCESS }
        - { path: ^/api/experts, roles: PUBLIC_ACCESS }
        - { path: ^/api/services, roles: PUBLIC_ACCESS }
        - { path: ^/api/owner-dashboard, roles: ROLE_OWNER }
        - { path: ^/api/expert-dashboard, roles: ROLE_EXPERT }
        - { path: ^api/client-dashboard, roles: ROLE_CLIENT }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/owner-dashboard, roles: ROLE_OWNER }
