services:
  - type: web
    name: trivialapps
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: 0
      - key: DATABASE_URL
        value: "pgsql://walter7:8RBiNn58Qdj16RSJWDX6Jpep9BTdpbki@dpg-cvkrjuruibrs73a5oa3g-a/trivialapps"
