# render.yaml
services:
  - type: web
    name: trivialapps
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: 0
      # Ajoute ici ta vraie URL de BDD Render si tu en as une :
      # - key: DATABASE_URL
      #   value: mysql://user:pass@host:3306/db
