# config/routes.yaml

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    # Exclure les routes API qui seront définies manuellement
    exclude: ['../src/Controller/Api/']

react_catch_all:
    path: /{reactRoute}
    controller: App\Controller\ReactController::index
    requirements:
        reactRoute: "^(?!api|_wdt|_profiler|build).+"
    defaults:
        reactRoute: null

api_services_list:
    path: /api/services
    controller: App\Controller\Api\ServiceController::list
    methods: GET

api_service_detail:
    path: /api/services/{id}
    controller: App\Controller\Api\ServiceController::detail
    methods: GET
    requirements:
        id: '\d+'  # Seulement les IDs numériques

# Authentification JWT
api_login:
    path: /api/login
    methods: POST
    controller: lexik_jwt_authentication.controllers.authentication:login

# Routes API sécurisées
api_invoices:
    path: /api/me/invoices
    controller: App\Controller\Api\InvoiceController::getInvoices
    methods: [GET]
    defaults:
        _format: json

api_unpaid_invoices:
    path: /api/me/invoices/unpaid
    controller: App\Controller\Api\InvoiceController::getUnpaidInvoices
    methods: [GET]
    defaults:
        _format: json